### ISSUE TITLE
ArgumentException: Version string portion was too short or too long.

### ISSUE THREAD

**Issue by Iconoclass** [Varneon/WorldCreatorAssistant#4]
4 red errors pop up in the console:

ArgumentException: Version string portion was too short or too long.
System.Version+VersionResult.SetFailure (System.Version+ParseFailureKind failure, System.String argument) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Version+VersionResult.SetFailure (System.Version+ParseFailureKind failure) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Version.TryParseVersion (System.String version, System.Version+VersionResult& result) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Version.Parse (System.String input) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Version..ctor (System.String version) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Varneon.WorldCreatorAssistant.UtilityMethods.ParseVersionText (System.String version) (at Assets/Varneon/WorldCreatorAssistant/Editor/UtilityMethods.cs:59)
Varneon.WorldCreatorAssistant.UtilityMethods.GetRepositoryDownloadStatus (System.String directory, System.String& version, System.Boolean& downloaded) (at Assets/Varneon/WorldCreatorAssistant/Editor/UtilityMethods.cs:199)
Varneon.WorldCreatorAssistant.UtilityMethods.GetRepositoryStatus (Varneon.WorldCreatorAssistant.DataStructs+Repository repository, System.String packageCacheDirectory) (at Assets/Varneon/WorldCreatorAssistant/Editor/UtilityMethods.cs:154)
Varneon.WorldCreatorAssistant.DataStructs+Repository.UpdateRepositoryStatus (System.String packageCacheDirectory) (at Assets/Varneon/WorldCreatorAssistant/Editor/DataStructs.cs:81)
Varneon.WorldCreatorAssistant.Importer.CheckRepositories (System.Collections.Generic.List`1[T] repositories) (at Assets/Varneon/WorldCreatorAssistant/Editor/Importer.cs:430)
Varneon.WorldCreatorAssistant.Importer..ctor (System.String packageCacheDir) (at Assets/Varneon/WorldCreatorAssistant/Editor/Importer.cs:375)
Varneon.WorldCreatorAssistant.WorldCreatorAssistant.OnEnable () (at Assets/Varneon/WorldCreatorAssistant/Editor/WorldCreatorAssistant.cs:44)
UnityEditor.EditorWindow:GetWindow()
Varneon.WorldCreatorAssistant.WindowOpener:OpenWindow() (at Assets/Varneon/WorldCreatorAssistant/Editor/WindowOpener.cs:12)

ArgumentNullException: Value cannot be null.
Parameter name: str
System.Text.RegularExpressions.Regex.Unescape (System.String str) (at <ef151b6abb5d474cb2c1cb8906a8b5a4>:0)
Varneon.WorldCreatorAssistant.WorldCreatorAssistant.DrawMainPage () (at Assets/Varneon/WorldCreatorAssistant/Editor/WorldCreatorAssistant.cs:135)
Varneon.WorldCreatorAssistant.WorldCreatorAssistant.OnGUI () (at Assets/Varneon/WorldCreatorAssistant/Editor/WorldCreatorAssistant.cs:79)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.DockArea.OldOnGUI () (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced.
UnityEngine.GUIUtility:ProcessEvent (int,intptr)

ArgumentNullException: Value cannot be null.
Parameter name: str
System.Text.RegularExpressions.Regex.Unescape (System.String str) (at <ef151b6abb5d474cb2c1cb8906a8b5a4>:0)
Varneon.WorldCreatorAssistant.WorldCreatorAssistant.DrawMainPage () (at Assets/Varneon/WorldCreatorAssistant/Editor/WorldCreatorAssistant.cs:135)
Varneon.WorldCreatorAssistant.WorldCreatorAssistant.OnGUI () (at Assets/Varneon/WorldCreatorAssistant/Editor/WorldCreatorAssistant.cs:79)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEditor.DockArea.OldOnGUI () (at <3d9f46ac475f4fa9a3b71bacf80244a8>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.IMGUIContainer.DoIMGUIRepaint () (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.UIR.RenderChainCommand.ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams drawParams, System.Boolean straightY, System.Single pixelsPerPoint, System.Exception& immediateException) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
Rethrow as ImmediateModeException
UnityEngine.UIElements.UIR.RenderChain.Render (UnityEngine.Rect viewport, UnityEngine.Matrix4x4 projection, UnityEngine.UIElements.PanelClearFlags clearFlags) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.UIRRepaintUpdater.DrawChain (UnityEngine.Rect viewport, UnityEngine.Matrix4x4 projection) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.UIRRepaintUpdater.Update () (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.Panel.UpdateForRepaint () (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.Panel.Repaint (UnityEngine.Event e) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <aea3cceceb0c44ea9855b62119e9be3b>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <023156577e4f4156adf0f4b3a3fedf85>:0)

**Comment by Varneon** [comment]
Looks like version file parsing of a community tool from the package cache has failed during the opening of the WCA window.

Have any of the files been modified manually in the package cache?

If you know a specific file that has been modified as in renamed or manually put it, delete it and try opening WCA again.

If the issue persists, try deleting the following folders in PackageCache:
- CyanEmu
- EasyQuestSwitch
- UdonSharp
- UdonToolkit
- VRWorldToolkit

File version parsing method is missing error handling and I will be adding that for the next release.

**Comment by Iconoclass** [comment]
I put the package cache folder inside the same Unity folder on accident. It still has 6 red errors when I set it up correctly but of course I understand it is in early alpha. This is a very useful tool that I am grateful for and am excited to see it develop.
